"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest

_HAS_SCITEX_DEV = shutil.which("scitex-dev") is not None


@pytest.mark.skipif(
    not _HAS_SCITEX_DEV,
    reason="scitex-dev not installed — add `scitex-dev[cli-audit]` to [dev]",
)
def test_audit_all_returns_clean_for_openalex_local():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    audit_all_for_package("openalex-local")
    audit_completed = True
    # Assert
    assert audit_completed
